config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'travels#index'

  resources :travels, only: [:index]
  get ':dim_actor_id/:dim_source_id', to: 'travels#show', as: :travel
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dim_actor.rb
#
class DimActor < ApplicationRecord
  ##
  # Validations
  validates :name, presence: true
  ##
  # Associations
  has_many :fact_travels

  scope :charge_order, lambda {
    order(
      'CASE charge
        WHEN \'PRESIDENTE DE LA REPÚBLICA\' THEN 1
        WHEN \'VICEPRESIDENTE\' THEN 2
        WHEN \'PRIMERA DAMA\' THEN 3
        WHEN \'OTROS\' THEN 4
        ELSE 5
     END'
    )
  }

  scope :period_order, lambda {
    order('LEFT(period, STRPOS(period, \'-\') - 1)::int')
  }

  scope :active, -> { where(active: true) }
end

app/models/dim_destination.rb
#
class DimDestination < ApplicationRecord
  #
  belongs_to :fact_travel

  def name
    cols = [city, country]
    return 'N/A' if cols.all?(&:blank?)

    sep = ', '
    sep = '' if cols.any?(&:blank?)
    [city, country].join(sep)
  end
end

app/models/dim_endorsement.rb
class DimEndorsement < ApplicationRecord
end

app/models/dim_source.rb
#
class DimSource < ApplicationRecord
  ##
  # Associations
  has_many :fact_travels

  NAMES = {
    1 => 'Asamblea',
    2 => 'EMP',
    3 => 'Migración',
    4 => 'RREE',
    5 => 'Jurídica',
    6 => 'CAPRES',
    7 => 'Medios',
    8 => 'DACI'
  }

  def acronym
    #source.scan(/\p{Upper}/).join('')
    NAMES[id]
  end
end

app/models/dim_time.rb
class DimTime < ApplicationRecord
  validates :year, :month, :month_str, presence: true

  before_validation(on: :create) do
    self.month_str = case month
    when 1
      "#{year} Ene"
    when 2
      "#{year} Feb"
    when 3
      "#{year} Mar"
    when 4
      "#{year} Abr"
    when 5
      "#{year} May"
    when 6
      "#{year} Jun"
    when 7
      "#{year} Jul"
    when 8
      "#{year} Ago"
    when 9
      "#{year} Sep"
    when 10
      "#{year} Oct"
    when 11
      "#{year} Nov"
    else
      "#{year} Dic"
    end
  end
end

app/models/fact_travel.rb
#
class FactTravel < ApplicationRecord
  ##
  # Validations
  validates :dim_time_id, :dim_actor_id, :dim_source_id, presence: true

  ##
  # Associations
  has_many :dim_destinations, dependent: :destroy
  belongs_to :dim_source

  scope :competent, lambda {
    where.not(departure_date: nil)
         .where.not(arrival_date: nil)
  }

  scope :actor_id, -> (actor_id) { where(dim_actor_id: actor_id) }

  scope :distincts, -> { select('distinct on (departure_date) *') }

  scope :overlapping, lambda { |other|
    where(
      [
        '(departure_date - ?) * (? - arrival_date) >= 0',
        other.arrival_date,
        other.departure_date
      ]
    )
  }

  def details
    str = ''
    str += "\nObjetivos: #{objectives}" if objectives.present?
    if dim_destinations.any?
      str += "\nDestinos: #{dim_source_id == 3 ? (is_departure != 1 ? 'Entrada a ' : 'Salida a ' ) : ''}#{dim_destinations.collect{|o| [o.country, o.city].compact.join(', ')}.join('. ')}"
    end
    if companions.present?
      str += "\nAcompañantes: #{companions_count.to_i > 0 ? "#{companions_count} en total. " : ''}#{companions}"
    end
    if cost.present?
      str += "\nCosto del boleto: $#{cost}."
    end
    if viaticum.present?
      str += "\nViáticos: $#{viaticum}."
      str += " Pagados el: #{viaticum_date.try(:strftime, '%d-%m-%Y')}." if viaticum_date
    end
    # str += .... if condition

    # If nothing was concated
    str = 'N/A' if str.blank?
    str
  end

  MIGRATION = {
    1 => 4,
    3 => 50,
    4 => 60,
    5 => 45,
    6 => 34,
    7 => 70,
    8 => 103,
    9 => 79,
    11 => 64,
    15 => 42,
    16 => 1,
    17 => 54,
    18 => 4,
    19 => 11,
    20 => 11,
    22 => 53,
    30 => 65,
    31 => 90
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/travels_controller.rb
#
class TravelsController < ApplicationController
  #
  before_action :init_table
  #
  def index
  end

  def show
    @fact_travels = FactTravel
                    .competent
                    .where(
                      params.permit(
                        :dim_actor_id,
                        :dim_source_id
                      )
                    )
                    .order(:departure_date)
    render template: 'travels/index'
  end

  def init_table
    @dim_actors  = DimActor.active.charge_order.period_order
    @dim_sources = DimSource.order(:source)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!! 5
%html{ lang: "es" }
  %head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui' }
    %meta{ name: 'apple-mobile-web-app-capable', content: 'yes' }

    %title= content_for?(:title) ? yield(:title) : "Viajes de presidentes de El Salvador"

    %link{ href: image_path('favicon.png'), sizes: '128x128', rel: 'shortcut icon' }
    %link{ href: image_path('favicon.png'), sizes: '128x128', rel: 'apple-touch-icon' }
    %link{ href: image_path('favicon.png'), sizes: '128x128', rel: 'apple-touch-icon-precomposed' }

    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags

  %body
    = render partial: 'layouts/application/header'
    %main
      = yield
    = render partial: 'layouts/application/footer'
    = render 'layouts/application/analytics'

app/views/layouts/application/_analytics.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-84809468-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/application/_footer.haml
%footer
  .container
    .row
      .col-xs-12.col-sm-4.col-md-3
        = image_tag 'gobierno-de-el-salvador.jpg'
      .col-xs-12.col-sm-4.col-md-4
        %p.contact-info
          Presidencia de la República de El Salvador
          %br
          Alameda Dr. Enrique Araujo, No. 5500.
          %br
          San Salvador, El Salvador, CA.
          %br
          Tel. +(503)2133-7500 | Email. info@gobiernoabierto.gob.sv
      .col-xs-12.col-sm-4.col-md-4
        .footer-cc-logo
          = image_tag 'icon-cc.png'
        %p.contact-info
          Gobierno Abierto by Secretaría de Participación Ciudadana,
          Transparencia y Anticorrupción is licensed under a Creative Commons
          %br
          Reconocimiento-CompartirIgual 4.0 Internacional License.
      .col-xs-12.col-sm-12.col-md-1
        .social
          = link_to 'https://www.facebook.com/GobiernoAbiertoSV', target: '_blank' do
            = image_tag 'icon-facebook.png'
          = link_to 'https://twitter.com/GobAbiertoSV', target: '_blank' do
            = image_tag 'icon-twitter.png'
          = mail_to 'info@gobiernoabierto.gob.sv' do
            = image_tag 'icon-mail.png'

app/views/layouts/application/_header.haml
%nav.navbar.navbar-default
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      = link_to root_url, class: 'navbar-brand' do
        = image_tag 'gobierno-abierto.png'
    / Collect the nav links, forms, and other content for toggling

app/views/travels/index.haml
- current_charge = nil
.container
  .row
    .col-xs-12.col-sm-12
      %h1.index-title
        Viajes presidenciales
      %br
      .table-responsive
        %table.table.table-striped
          %thead
            %tr
              %th{ rowspan: 2}
                Funcionario
              %th{ rowspan: 2}
                Cargo
              %th{ rowspan: 2}
                Período
              -#
                %th{ rowspan: 2}
                  Viajes
              %th{ colspan: @dim_sources.count, class: 'centered' }
                Fuente
              %th{ rowspan: 2 }
                Total
            %tr
              - @dim_sources.each do |dim_source|
                %th.centered.data{ title: dim_source.source }
                  = dim_source.acronym

            - @dim_actors.each do |dim_actor|
              - change_charge  = true if !current_charge.nil? && dim_actor.charge != current_charge
              - current_charge = dim_actor.charge
              - travels = dim_actor.fact_travels.competent.distincts

              - if change_charge
                %tr
                  %td.separator{ colspan: 4 + @dim_sources.count }
              %tr{ class: action_name == 'show' && params[:dim_actor_id].to_i == dim_actor.id ? 'selected' : 'warning' }
                %td{ id: "a#{dim_actor.id}" }
                  = dim_actor.name
                %td
                  = dim_actor.charge
                %td
                  = dim_actor.period
                -#
                  %td
                    = travels.length

                - @dim_sources.each do |dim_source|
                  %td.centered
                    = link_to travel_url(dim_actor.id, dim_source.id, anchor: "a#{dim_actor.id}") do
                      - if dim_source.id == 3
                        = FactTravel::MIGRATION[dim_actor.id]
                      - else
                        = dim_source.fact_travels.competent.actor_id(dim_actor.id).count
                %td
                  = dim_actor.fact_travels.competent.where.not(dim_source_id: 3).count + FactTravel::MIGRATION[dim_actor.id]
              - if action_name == 'show' && params[:dim_actor_id].to_i == dim_actor.id
                %tr
                  %td.no-padding{ colspan: 4 + @dim_sources.count }
                    %table.table
                      %thead
                        %tr
                          %th
                            Destino
                          %th
                            Fecha
                          %th
                            Detalles
                          - @dim_sources.each do |dim_source|
                            %th.centered.data{ title: dim_source.source }
                              = link_to travel_url(dim_actor.id, dim_source.id, anchor: "a#{dim_actor.id}"), class: (params[:dim_source_id].to_i == dim_source.id ? 'selected' : nil) do
                                = dim_source.acronym

                      - @fact_travels.each do |travel|
                        %tr
                          %td
                            %ul
                              - if travel.dim_destinations.any?
                                - travel.dim_destinations.each do |destination|
                                  %li
                                    = destination.name
                              - else
                                N/A
                          %td.nowrap
                            = travel.departure_date
                            \-
                            = travel.arrival_date
                          %td.small
                            = simple_format travel.details
                          - @dim_sources.each do |dim_source|
                            %td.centered
                              - if travels.where(dim_source_id: dim_source.id).overlapping(travel).exists?
                                %span.text-green.glyphicon.glyphicon-ok
                              - else
                                %span.text-red.glyphicon.glyphicon-remove